# fly.toml
app = "FlySafetyExpertBot"  # ← замените на имя вашего приложения в fly.io

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]  # ← это ключевая строка!

[http_service]
  internal_port = 8080  # ← порт, который слушает ваше приложение (например, Flask)
  force_https = true
